### ISSUE TITLE
INTERFAS GRAFICA 

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/practica-de-visual-studio-javiern-778#2]
[Practica 2_ Interfas Grafica .pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-javiern-778/files/6205549/Practica.2_.Interfas.Grafica.pdf)

**Comment by Eva155** [comment]
Calificación: 19 puntos
Calificó: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado
